name: 'Python Docker Action'
description: 'Runs a Python script inside a Docker container'
inputs:
  do-token:
    description: 'DigitalOcean Personal Access Token (PAT)'
    required: true
  repository-name:
    description: 'repository that you want to run untag'
    required: true
  days:
    description: 'Number of days for keeping images. Default to 7 if not specific keep-latest'
    required: false
    default: 7
  months:
    description: 'Untag versions from imgages older than keep_latest images, Default to 0 (Disable)'
    required: false
    default: 6


runs:
  using: 'docker'
  image: 'docker://ghcr.io/thegangtechnology/digitalocean-image-registry-cleaner:jv-custom'
  env:
    DO_TOKEN: ${{ inputs.do-token }}
    REPOSITORY_NAME: ${{ inputs.repository-name }}
    DAYS: ${{ inputs.days }}
    MONTHS: ${{ inputs.months }}
  args:
    - ${{ inputs.do-token }}
    - ${{ inputs.repository-name }}
    - ${{ inputs.days }}
    - ${{ inputs.months }}