name: 'Python Docker Action'
description: 'Runs a Python script inside a Docker container'
inputs:
  do-token:
    description: 'DigitalOcean Personal Access Token (PAT)'
    required: true
  repository-name:
    description: 'repository that you want to run untag'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    DO_TOKEN: ${{ inputs.do-token }}
    REPOSITORY_NAME: ${{ inputs.repository-name }}
  args:
    - ${{ inputs.do-token }}
    - ${{ inputs.repository-name }}