name: "Untag image"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on:  [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Python Docker Action
        uses: thegangtechnology/do-optimize-registry/untag-image@main
        with:
          do-token: ${{ secrets.DO_TOKEN }}
          repository-name: tt-exchange
