name: "Run test arc"
on:
  push:
    branches:
      - jeep/test-arc

jobs:
  build:
    runs-on: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display current directory
        run: pwd

